# Generated by Django 4.0.3 on 2022-05-07 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movieshorts_image_alter_movieshorts_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MovieShorts',
            new_name='MovieShots',
        ),
    ]
