# Generated by Django 4.0.3 on 2022-05-16 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_rename_movieshorts_movieshots'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratingstar',
            options={'ordering': ['-value'], 'verbose_name': 'Звезад рейтинга', 'verbose_name_plural': 'Звезды рейтинга'},
        ),
    ]
