# Generated by Django 4.0.3 on 2022-06-03 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_actor_description_en_actor_description_es_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='description_es',
        ),
        migrations.RemoveField(
            model_name='actor',
            name='name_es',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description_es',
        ),
        migrations.RemoveField(
            model_name='category',
            name='name_es',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='description_es',
        ),
        migrations.RemoveField(
            model_name='genre',
            name='name_es',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='country_es',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='description_es',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='tagline_es',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='title_es',
        ),
        migrations.RemoveField(
            model_name='movieshots',
            name='description_es',
        ),
        migrations.RemoveField(
            model_name='movieshots',
            name='title_es',
        ),
    ]
